version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    container_name: book-creation-mongodb-container
    networks:
      - book-creation-service-network
    volumes:
      - type: volume
        source: mongodb_data
        target: /data/db

networks:
  book-creation-service-network:
    driver: bridge

volumes:
  mongodb_data:
